# Generated by Django 3.2.19 on 2026-02-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название окружения')),
            ],
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('fname', models.FileField(upload_to='', verbose_name='Файл модели')),
                ('fname_obj', models.FileField(upload_to='', verbose_name='Файл с материалами модели')),
                ('height', models.IntegerField(verbose_name='Высота объекта, м')),
                ('descr', models.CharField(max_length=300, verbose_name='Краткое описание модели')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сцены')),
                ('fname_json', models.CharField(max_length=100, verbose_name='Название файла JSON')),
                ('envir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadmodels.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('scaleX', models.IntegerField()),
                ('scaleY', models.IntegerField()),
                ('scaleZ', models.IntegerField()),
                ('rotX', models.IntegerField()),
                ('rotY', models.IntegerField()),
                ('rotZ', models.IntegerField()),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadmodels.model3d')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadmodels.scene')),
            ],
        ),
    ]
