# Generated by Django 3.2.19 on 2026-02-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='fname',
            field=models.FileField(upload_to='loadmodels/static/models', verbose_name='Файл модели'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='fname_obj',
            field=models.FileField(upload_to='loadmodels/static/models', verbose_name='Файл с материалами модели'),
        ),
    ]
