# Generated by Django 3.2.19 on 2026-02-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadmodels', '0002_auto_20260218_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model3d',
            old_name='fname_obj',
            new_name='fname_mtl',
        ),
    ]
