# Generated by Django 3.2.19 on 2026-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadmodels', '0003_rename_fname_obj_model3d_fname_mtl'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='map_image',
            field=models.FileField(default='blank_map.png', upload_to='loadmodels/static/images/maps/', verbose_name='Файл изображения карты'),
        ),
    ]
