# Generated by Django 3.2.19 on 2026-02-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadmodels', '0004_scene_map_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название текстуры')),
                ('fname', models.FileField(upload_to='loadmodels/static/models/textures/', verbose_name='Файл текстуры')),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadmodels.model3d', verbose_name='3D  модель')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('fname_info', models.FileField(upload_to='templates/history_info/', verbose_name='Файл html  с исторической справкой')),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadmodels.model3d', verbose_name='3D  модель')),
            ],
        ),
    ]
