# Generated by Django 3.2.19 on 2026-02-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadmodels', '0005_historyinfo_textureimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='scene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loadmodels.scene'),
        ),
    ]
