# Generated by Django 3.2.19 on 2026-02-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadmodels', '0006_model3d_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='scene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loadmodels.scene', verbose_name='3D сцена'),
        ),
        migrations.CreateModel(
            name='Model3DSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmin', models.FloatField()),
                ('xmax', models.FloatField()),
                ('ymin', models.FloatField()),
                ('ymax', models.FloatField()),
                ('zmin', models.FloatField()),
                ('zmax', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadmodels.model3d')),
            ],
        ),
    ]
