# Generated by Django 3.2.19 on 2026-02-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadmodels', '0007_auto_20260221_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripOnScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadmodels.scene', verbose_name='3В сцена')),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.CharField(max_length=200)),
                ('Y', models.CharField(max_length=200)),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadmodels.model3d')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadmodels.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('phi', models.IntegerField()),
                ('theta', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadmodels.triponscene')),
            ],
        ),
    ]
