# Generated by Django 3.2.19 on 2026-02-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadmodels', '0008_coord_polygon_triponscene'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='color',
            field=models.CharField(default='rgb(255,0,0,1.0)', max_length=200),
        ),
    ]
