# Generated by Django 3.2.19 on 2026-03-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadmodels', '0009_polygon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='scale',
            field=models.FloatField(default=1, verbose_name='Масштаб - отношение истинного расстояния к пиксельному'),
        ),
    ]
